server {
    listen 80;
    server_name _;

    location /tiles/ {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Expose-Headers "Content-Length,Content-Range" always;
        add_header Cache-Control "public, max-age=3600" always;
    }
}
